### ISSUE TITLE
Minor broken text, episode 4 text largely non-existent

### ISSUE THREAD

**Issue by Yackerw** [Solybum/Blue-Burst-Patch-Project#5]
Trying to use the files from the old tethealla client version 12513 and connecting to newserv, the create a party selections omit episode 4 (though you can still select it by continuing to scroll) and pretty much all episode 4 specific text seems to not load. Likewise, the text for options in create a party are somewhat broken, showing the wrong text. Playing on the actual tethealla 12513 client, everything seems to work fine? Is this a case of "I need different files", or what?

**Comment by Solybum** [comment]
I would say it is the files you are using, because none of our patches affect the game in that way, also the bundled client bundled, is a 12513 client with a little asm patch to load the dll and nothing else.

However, I have only tested this with a tethealla server as well as my own Aselia (which is based on tethealla mostly).

**Comment by Yackerw** [comment]
Indeed, an un-modified 12513 is the same client I'm using that DOES work with the same files. Having tested tethealla as well now, it still occurs. Confused.

**Comment by Yackerw** [comment]
Update: I figured out the issue. For some reason, in the patched exe, the string for unitxt_j.prs has been replaced with a duplicate for unitxt_e.prs. No idea why this matters, no idea why it breaks everything relating to episode 4, and no idea if this means the tethealla download I have has incomplete files or anything...but it seems like unintended behaviour regardless?

**Comment by ShiftaDeband** [comment]
It's possible that your unitxt_e.prs is outdated, or your unitxt_j.prs is just a renamed unitxt_e.prs, which it was looking for in the first place. Several repackaged clients seem to do this to simplify things. Heck, I've seen repackaged CN clients do this. (but you'll see yourself in the lobby as YourName J001) 

I think the data.gsl version of unitxt_e.prs is also outdated, which may also explain the issue if you don't have a current unitxt_e.prs in your data/ directory.

If you want to have some fun, try loading any other language unitxt_*.prs (aside from J, of course) and they'll be using their text from the Episode I&II era, missing a ton of text as well. 

Either way, it's however your files were packaged in the first place. You may be able to simply fix it by renaming your unitxt, unless fixing the string in the executable fixed it?

**Comment by Yackerw** [comment]
Yes, simply fixing the string in the executable fixed it.

**Comment by Solybum** [comment]
ahh it might be possible I left that in from previous binary patches in the client... or the dll is doing it, not sure.

But yeah, at least the way I do it, is to have each unitxt file with the respective language, instead of overwriting unitxt_j, I just change the string to use the selected language.

I think I'll leave the string as is for now, if it becomes a bigger issue later on, I can look into updating the bundled executable... or even better just add the override in the dll so people can change it there.
